In [147]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 100)
%matplotlib inline

In [148]:
df = pd.read_csv('vectorized_model_data.csv')

In [149]:
recipe_data = pd.read_csv('recipe_data.csv')

In [150]:
df.shape

(39774, 917)

In [151]:
recipe_data.shape

(39774, 6)

In [152]:
recipe_total = 39774

In [153]:
recipe_data.groupby('cuisine')['cuisine'].count()

cuisine
brazilian        467
british          804
cajun_creole    1546
chinese         2673
filipino         755
french          2646
greek           1175
indian          3003
irish            667
italian         7838
jamaican         526
japanese        1423
korean           830
mexican         6438
moroccan         821
russian          489
southern_us     4320
spanish          989
thai            1539
vietnamese       825
Name: cuisine, dtype: int64

In [154]:
cuisine_counts = {
    'brazilian':467,
    'british':804,
    'cajun_creole':546,
    'chinese':2673,
    'filipino':755,
    'french':2646,
    'greek':1175,
    'indian':3003,
    'irish':667,
    'italian':7838,
    'jamaican':526,
    'japanese':1423,
    'korean':830,
    'mexican':6438,
    'moroccan':821,
    'russian':489,
    'southern_us':4320,
    'spanish':989,
    'thai':1539,
    'vietnamese':825   
}

In [155]:
cuisine_percentages = {}
for key in cuisine_counts:
    cuisine_percentages[key] = cuisine_counts[key] / recipe_total

In [156]:
cuisine_percentages

{'brazilian': 0.011741338562880274,
 'british': 0.020214210288127924,
 'cajun_creole': 0.013727560718057022,
 'chinese': 0.06720470659224619,
 'filipino': 0.018982249710866397,
 'french': 0.0665258711721225,
 'greek': 0.02954191180167949,
 'indian': 0.07550158394931362,
 'irish': 0.01676974908231508,
 'italian': 0.19706340825665009,
 'jamaican': 0.013224719666113542,
 'japanese': 0.03577714084577865,
 'korean': 0.020867903655654448,
 'mexican': 0.16186453462060643,
 'moroccan': 0.020641625182279882,
 'russian': 0.012294463720018103,
 'southern_us': 0.10861366721979182,
 'spanish': 0.024865490018605118,
 'thai': 0.03869361894705084,
 'vietnamese': 0.020742193392668577}

In [157]:
df['cuisine'] = recipe_data['cuisine']

In [158]:
ingredient_counts = df.groupby('cuisine').sum().reset_index()

In [159]:
#' mozzarella' and &half didn't work, so drop them
ingredient_counts.drop([' mozzarella', '& half'], axis=1, inplace=True)

In [160]:
ingredient_counts.head(20)

,cuisine,active yeast,adobo sauce,agave nectar,alfredo sauce,allspice,almond,almond extract,almond flour,almond milk,amchur,american cheese,anaheim chile,ancho,ancho chile pepper,anchovy,anchovy paste,andouille sausage,angel hair,anise,anise seed,apple,apple cider,apple juice,apricot,arborio rice,artichoke,artichoke heart,arugula,asafetida,asafoetida,asiago,asparagu,asparagu spear,avocado,bacon,bacon dripping,baguette,baking,baking potato,baking soda,balsamic vinegar,bamboo shoot,banana,barbecue sauce,base,basil,basmati rice,bay,bay scallop,...,turmeric,turnip,udon,urad dal,vanilla,vanilla bean,vanilla extract,vanilla pudding,vanilla wafer,veal,vegetable,vegetable broth,vegetable oil,vegetable shortening,vegetable stock,veggie,velveeta,vermicelli,vermouth,vidalia onion,vinaigrette,vinegar,vodka,walnut,warm water,wasabi,wasabi paste,water,water chestnut,watercres,watermelon,waxy potato,wheat bread,wheat flour,wheat tortilla,whipped cream,whipped topping,whiskey,whitefish,wild mushroom,wine,wine vinegar,wonton wrapper,wood ear,worcestershire sauce,yam,yeast,yogurt,yukon gold,zucchini
0,brazilian,3,0,4,0,1,24,0,0,13,0,0,0,1,0,0,0,1,0,2,1,10,1,1,1,0,0,0,0,0,0,0,0,0,10,30,0,2,19,0,5,0,0,30,0,0,2,3,54,1,...,4,0,0,0,28,4,18,0,0,0,46,1,43,0,2,0,0,0,0,0,0,26,4,1,2,0,0,112,0,0,1,0,0,2,0,4,0,0,1,0,30,13,0,0,2,0,6,4,1,3
1,british,13,0,0,0,27,44,11,1,1,0,0,0,0,0,1,0,0,0,1,0,30,1,0,14,0,1,0,3,0,0,0,1,0,0,25,2,0,214,13,73,16,0,15,0,0,5,6,42,0,...,3,5,0,0,119,10,66,3,1,8,82,1,64,10,3,0,0,0,2,0,0,71,0,21,15,0,0,178,0,5,0,0,2,11,0,78,2,4,2,1,66,12,0,0,53,0,41,11,9,3
2,cajun_creole,36,0,0,5,18,12,2,1,0,0,2,0,2,0,5,3,228,4,0,0,15,6,0,0,3,10,4,2,0,0,1,6,1,4,62,7,11,62,4,23,8,1,6,6,4,94,8,360,4,...,1,4,0,0,74,2,48,0,0,2,313,21,265,4,5,0,2,1,2,4,2,72,3,0,24,0,0,340,2,6,0,0,2,0,0,40,0,10,1,2,105,32,1,0,195,0,56,3,2,13
3,chinese,12,0,4,0,0,46,8,5,0,0,0,0,0,0,0,0,0,4,111,1,26,23,1,4,1,0,0,1,0,0,0,20,3,9,26,0,1,100,1,46,32,77,1,11,5,34,10,14,2,...,6,11,10,0,22,0,14,1,0,0,723,27,612,3,12,4,0,21,0,1,2,870,7,13,34,0,0,1129,145,8,0,0,0,2,0,6,0,3,1,1,693,75,127,21,39,7,33,2,0,32
4,filipino,7,1,0,0,1,2,1,0,0,0,1,1,0,0,0,0,0,2,13,0,24,20,0,1,1,0,0,0,0,0,0,0,0,3,4,1,0,30,0,2,3,8,40,1,8,2,0,122,0,...,5,0,0,0,37,2,25,0,0,0,108,7,95,3,1,2,2,3,0,0,0,172,0,0,9,0,0,348,15,0,0,0,0,0,0,1,0,0,1,0,17,5,8,0,9,6,17,0,2,6
5,french,40,0,1,1,38,176,44,13,3,0,0,0,1,0,71,11,0,2,16,4,128,13,5,37,1,28,17,13,0,0,5,48,14,3,145,2,78,125,37,16,35,0,16,0,3,159,0,303,5,...,2,24,0,0,403,82,238,4,0,33,169,18,131,8,2,0,0,2,13,9,13,327,3,49,45,0,0,661,0,11,1,4,7,9,0,225,10,10,6,7,663,194,0,0,20,0,76,25,43,90
6,greek,6,0,2,0,32,29,3,0,0,0,0,0,0,0,5,2,0,4,10,4,5,2,0,3,0,29,21,10,0,0,0,2,0,6,3,0,3,68,12,17,24,2,5,0,1,76,8,38,0,...,5,0,0,0,35,2,28,0,0,4,55,5,42,0,3,0,0,0,3,1,12,172,0,33,16,0,0,185,2,2,1,2,0,3,2,3,0,1,0,0,199,113,0,0,3,0,15,293,4,49
7,indian,34,1,4,0,24,124,1,4,8,69,0,1,1,0,0,0,0,0,52,3,46,9,3,14,0,0,0,1,43,100,0,6,0,5,0,0,1,109,23,37,6,1,19,0,0,15,253,231,0,...,732,6,0,69,18,2,11,0,0,1,743,60,602,3,39,5,0,6,0,2,3,153,4,2,60,0,0,967,0,4,1,7,1,71,3,22,0,0,7,0,55,38,1,0,2,6,73,810,27,43
8,irish,1,1,0,0,20,13,7,0,0,0,0,0,0,0,0,0,0,0,3,1,32,6,6,8,0,0,0,0,0,0,1,3,2,2,63,1,2,255,23,115,6,0,2,0,0,3,0,51,0,...,0,10,0,0,51,3,33,1,1,0,71,6,55,3,4,0,0,0,2,0,0,41,0,11,7,0,0,121,0,2,0,0,1,38,0,30,2,40,0,1,30,10,0,0,23,0,6,12,24,4
9,italian,128,1,2,67,12,266,56,15,6,0,5,0,1,0,202,47,2,67,41,13,36,11,6,32,263,187,141,160,0,0,72,176,24,25,233,0,153,292,34,68,357,0,12,9,5,2005,2,274,12,...,2,2,0,0,326,28,241,6,3,129,541,105,348,5,32,6,3,16,32,19,23,774,30,109,183,0,0,1483,3,16,7,2,14,28,1,256,13,8,4,30,1521,318,27,0,60,2,248,38,40,340
10,jamaican,2,1,0,0,195,3,1,1,0,0,0,0,0,0,0,0,0,1,3,1,8,7,0,0,0,0,0,0,0,0,0,0,0,6,10,0,0,49,0,11,1,0,28,6,1,8,2,21,0,...,13,2,0,0,37,0,22,1,0,0,121,3,99,5,7,2,0,0,1,2,0,90,2,0,5,0,0,210,0,0,0,1,0,0,0,3,0,1,1,0,24,15,1,0,10,11,12,3,2,5
11,japanese,2,0,11,0,1,13,2,1,1,17,0,0,0,0,2,0,0,2,5,0,18,5,0,1,0,1,0,6,7,6,0,23,8,60,8,0,1,55,0,16,4,13,4,1,12,10,2,24,2,...,34,8,45,2,20,1,18,0,1,0,292,18,250,0,6,2,0,3,0,0,0,337,2,5,11,87,38,479,4,14,1,1,0,12,0,2,0,0,2,2,65,25,2,3,22,5,7,10,6,18
12,korean,0,0,6,0,0,1,0,0,0,0,0,0,0,0,19,0,0,0,1,0,32,6,7,1,0,0,0,2,0,0,0,8,2,2,8,0,0,10,0,5,4,1,0,2,136,2,1,3,0,...,0,1,4,0,4,0,3,0,0,0,135,6,122,0,1,1,0,7,0,0,1,216,1,7,4,3,0,278,2,7,1,0,0,0,1,0,0,0,1,0,84,7,6,0,1,0,2,1,0,54
13,mexican,17,85,28,1,66,83,6,4,3,0,27,37,216,0,5,1,2,6,40,18,92,69,4,7,1,4,4,6,0,0,0,10,3,1103,127,5,6,219,10,31,24,1,29,27,8,63,9,188,2,...,10,1,0,0,150,18,97,1,0,1,996,90,833,19,25,7,18,8,2,16,4,435,3,13,55,2,1,1099,1,9,9,2,1,7,84,63,2,5,13,1,160,126,19,0,67,7,33,122,14,147
14,moroccan,8,0,0,0,44,111,1,0,0,0,0,2,2,0,1,0,0,2,9,5,7,2,1,95,0,6,3,7,0,0,0,1,0,2,0,0,1,11,2,0,5,0,1,0,0,9,6,23,0,...,73,24,0,0,6,0,2,0,0,1,118,44,44,0,24,0,0,6,0,4,1,41,2,7,20,0,0,253,0,1,0,1,0,1,0,2,0,0,2,0,51,21,0,0,0,5,20,36,10,40
15,russian,35,0,2,0,8,26,5,0,0,0,0,0,1,0,1,0,0,0,1,0,31,3,1,15,0,0,0,1,0,0,0,1,0,2,11,0,0,74,11,24,4,2,0,0,2,6,2,39,0,...,0,6,0,0,63,7,35,0,0,6,91,7,70,0,5,0,1,0,0,0,0,74,6,26,22,0,0,167,0,2,0,4,0,5,0,15,0,0,0,1,38,28,1,0,6,0,57,13,6,2
16,southern_us,29,4,7,0,59,70,23,10,5,1,4,2,8,0,0,0,36,0,5,1,233,110,20,11,3,3,1,7,1,0,5,6,0,13,431,47,13,1231,18,447,29,1,77,70,15,82,5,192,0,...,12,39,0,0,778,18,538,21,40,3,658,29,528,74,5,0,6,0,5,48,9,459,14,30,31,2,0,895,3,4,18,0,2,36,0,182,28,191,0,3,161,70,0,0,182,9,40,42,8,14
17,spanish,4,0,1,0,4,94,2,3,1,0,0,3,11,0,10,0,6,2,5,1,24,0,4,8,21,17,11,4,0,0,1,10,1,23,24,1,31,33,20,3,24,0,3,0,2,35,2,93,0,...,3,3,0,0,47,8,32,0,0,5,80,12,49,2,4,0,0,1,2,8,3,214,2,2,8,0,0,206,0,3,5,5,2,1,0,15,0,0,1,0,270,95,1,0,14,2,12,11,22,19
18,thai,1,0,5,0,1,8,0,1,0,0,0,5,1,0,3,3,0,3,12,0,18,9,3,2,0,0,0,1,0,0,0,23,3,14,1,0,1,7,0,2,4,24,13,1,7,334,20,14,3,...,41,6,4,0,3,0,1,0,0,0,413,30,338,0,22,2,0,25,0,1,2,233,0,1,9,0,0,381,18,10,2,1,0,1,3,3,0,0,11,0,50,23,3,0,4,2,2,8,4,46
19,vietnamese,1,0,6,0,4,4,0,1,0,0,0,0,0,0,0,0,0,0,65,1,11,7,0,1,0,0,0,0,0,0,0,4,1,14,2,0,34,9,0,1,1,6,12,0,3,162,2,9,0,...,19,5,1,0,4,0,3,0,0,0,171,4,145,0,6,1,0,73,0,0,2,195,0,2,24,0,0,298,2,8,1,1,0,3,1,0,0,0,1,1,33,9,3,11,1,1,2,2,1,3

In [161]:
ic2 = ingredient_counts.set_index('cuisine').T

In [162]:
ic2.head()

cuisine,brazilian,british,cajun_creole,chinese,filipino,french,greek,indian,irish,italian,jamaican,japanese,korean,mexican,moroccan,russian,southern_us,spanish,thai,vietnamese
active yeast,3,13,36,12,7,40,6,34,1,128,2,2,0,17,8,35,29,4,1,1
adobo sauce,0,0,0,0,1,0,0,1,1,1,1,0,0,85,0,0,4,0,0,0
agave nectar,4,0,0,4,0,1,2,4,0,2,0,11,6,28,0,2,7,1,5,6
alfredo sauce,0,0,5,0,0,1,0,0,0,67,0,0,0,1,0,0,0,0,0,0
allspice,1,27,18,0,1,38,32,24,20,12,195,1,0,66,44,8,59,4,1,4

In [163]:
raw_counts = ic2.reset_index().rename(columns={'index':'ingredient'})

In [164]:
raw_counts.head(40)

cuisine,ingredient,brazilian,british,cajun_creole,chinese,filipino,french,greek,indian,irish,italian,jamaican,japanese,korean,mexican,moroccan,russian,southern_us,spanish,thai,vietnamese
0,active yeast,3,13,36,12,7,40,6,34,1,128,2,2,0,17,8,35,29,4,1,1
1,adobo sauce,0,0,0,0,1,0,0,1,1,1,1,0,0,85,0,0,4,0,0,0
2,agave nectar,4,0,0,4,0,1,2,4,0,2,0,11,6,28,0,2,7,1,5,6
3,alfredo sauce,0,0,5,0,0,1,0,0,0,67,0,0,0,1,0,0,0,0,0,0
4,allspice,1,27,18,0,1,38,32,24,20,12,195,1,0,66,44,8,59,4,1,4
5,almond,24,44,12,46,2,176,29,124,13,266,3,13,1,83,111,26,70,94,8,4
6,almond extract,0,11,2,8,1,44,3,1,7,56,1,2,0,6,1,5,23,2,0,0
7,almond flour,0,1,1,5,0,13,0,4,0,15,1,1,0,4,0,0,10,3,1,1
8,almond milk,13,1,0,0,0,3,0,8,0,6,0,1,0,3,0,0,5,1,0,0
9,amchur,0,0,0,0,0,0,0,69,0,0,0,17,0,0,0,0,1,0,0,0
10,american cheese,0,0,2,0,1,0,0,0,0,5,0,0,0,27,0,0,4,0,0,0
11,anaheim chile,0,0,0,0,1,0,0,1,0,0,0,0,0,37,2,0,2,3,5,0
12,ancho,1,0,2,0,0,1,0,1,0,1,0,0,0,216,2,1,8,11,1,0
13,ancho chile pepper,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,anchovy,0,1,5,0,0,71,5,0,0,202,0,2,19,5,1,1,0,10,3,0
15,anchovy paste,0,0,3,0,0,11,2,0,0,47,0,0,0,1,0,0,0,0,3,0
16,andouille sausage,1,0,228,0,0,0,0,0,0,2,0,0,0,2,0,0,36,6,0,0
17,angel hair,0,0,4,4,2,2,4,0,0,67,1,2,0,6,2,0,0,2,3,0
18,anise,2,1,0,111,13,16,10,52,3,41,3,5,1,40,9,1,5,5,12,65
19,anise seed,1,0,0,1,0,4,4,3,1,13,1,0,0,18,5,0,1,1,0,1
20,apple,10,30,15,26,24,128,5,46,32,36,8,18,32,92,7,31,233,24,18,11
21,apple cider,1,1,6,23,20,13,2,9,6,11,7,5,6,69,2,3,110,0,9,7
22,apple juice,1,0,0,1,0,5,0,3,6,6,0,0,7,4,1,1,20,4,3,0
23,apricot,1,14,0,4,1,37,3,14,8,32,0,1,1,7,95,15,11,8,2,1
24,arborio rice,0,0,3,1,1,1,0,0,0,263,0,0,0,1,0,0,3,21,0,0
25,artichoke,0,1,10,0,0,28,29,0,0,187,0,1,0,4,6,0,3,17,0,0
26,artichoke heart,0,0,4,0,0,17,21,0,0,141,0,0,0,4,3,0,1,11,0,0
27,arugula,0,3,2,1,0,13,10,1,0,160,0,6,2,6,7,1,7,4,1,0
28,asafetida,0,0,0,0,0,0,0,43,0,0,0,7,0,0,0,0,1,0,0,0
29,asafoetida,0,0,0,0,0,0,0,100,0,0,0,6,0,0,0,0,0,0,0,0
30,asiago,0,0,1,0,0,5,0,0,1,72,0,0,0,0,0,0,5,1,0,0
31,asparagu,0,1,6,20,0,48,2,6,3,176,0,23,8,10,1,1,6,10,23,4
32,asparagu spear,0,0,1,3,0,14,0,0,2,24,0,8,2,3,0,0,0,1,3,1
33,avocado,10,0,4,9,3,3,6,5,2,25,6,60,2,1103,2,2,13,23,14,14
34,bacon,30,25,62,26,4,145,3,0,63,233,10,8,8,127,0,11,431,24,1,2
35,bacon dripping,0,2,7,0,1,2,0,0,1,0,0,0,0,5,0,0,47,1,0,0
36,baguette,2,0,11,1,0,78,3,1,2,153,0,1,0,6,1,0,13,31,1,34
37,baking,19,214,62,100,30,125,68,109,255,292,49,55,10,219,11,74,1231,33,7,9
38,baking potato,0,13,4,1,0,37,12,23,23,34,0,0,0,10,2,11,18,20,0,0
39,baking soda,5,73,23,46,2,16,17,37,115,68,11,16,5,31,0,24,447,3,2,1

In [165]:
#calculate percentages

In [166]:
pct_counts = raw_counts.copy()

In [167]:
#change ingredient counts to ingredient percentages
for i, row in pct_counts.iterrows():
    #print(i, row['ingredient'])
    for key, val in cuisine_counts.items():
        #key - the cuisine
        #val - the total number of recipes of that cuisine
        #row[key] - the number of recipes of that cuisine with the ingredient
        #row[key] / val - perecentage of recipes with the ingredient 
        #print (key, val, row[key], row[key]/val)  
        percentage = row[key]/val
        pct_counts.loc[i, key] = percentage

In [168]:
pct_counts.shape

(915, 21)

In [169]:
pct_counts.head(20)

cuisine,ingredient,brazilian,british,cajun_creole,chinese,filipino,french,greek,indian,irish,italian,jamaican,japanese,korean,mexican,moroccan,russian,southern_us,spanish,thai,vietnamese
0,active yeast,0.006424,0.016169,0.065934,0.004489,0.009272,0.015117,0.005106,0.011322,0.001499,0.016331,0.003802,0.001405,0.000000,0.002641,0.009744,0.071575,0.006713,0.004044,0.000650,0.001212
1,adobo sauce,0.000000,0.000000,0.000000,0.000000,0.001325,0.000000,0.000000,0.000333,0.001499,0.000128,0.001901,0.000000,0.000000,0.013203,0.000000,0.000000,0.000926,0.000000,0.000000,0.000000
2,agave nectar,0.008565,0.000000,0.000000,0.001496,0.000000,0.000378,0.001702,0.001332,0.000000,0.000255,0.000000,0.007730,0.007229,0.004349,0.000000,0.004090,0.001620,0.001011,0.003249,0.007273
3,alfredo sauce,0.000000,0.000000,0.009158,0.000000,0.000000,0.000378,0.000000,0.000000,0.000000,0.008548,0.000000,0.000000,0.000000,0.000155,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,allspice,0.002141,0.033582,0.032967,0.000000,0.001325,0.014361,0.027234,0.007992,0.029985,0.001531,0.370722,0.000703,0.000000,0.010252,0.053593,0.016360,0.013657,0.004044,0.000650,0.004848
5,almond,0.051392,0.054726,0.021978,0.017209,0.002649,0.066515,0.024681,0.041292,0.019490,0.033937,0.005703,0.009136,0.001205,0.012892,0.135201,0.053170,0.016204,0.095046,0.005198,0.004848
6,almond extract,0.000000,0.013682,0.003663,0.002993,0.001325,0.016629,0.002553,0.000333,0.010495,0.007145,0.001901,0.001405,0.000000,0.000932,0.001218,0.010225,0.005324,0.002022,0.000000,0.000000
7,almond flour,0.000000,0.001244,0.001832,0.001871,0.000000,0.004913,0.000000,0.001332,0.000000,0.001914,0.001901,0.000703,0.000000,0.000621,0.000000,0.000000,0.002315,0.003033,0.000650,0.001212
8,almond milk,0.027837,0.001244,0.000000,0.000000,0.000000,0.001134,0.000000,0.002664,0.000000,0.000766,0.000000,0.000703,0.000000,0.000466,0.000000,0.000000,0.001157,0.001011,0.000000,0.000000
9,amchur,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.022977,0.000000,0.000000,0.000000,0.011947,0.000000,0.000000,0.000000,0.000000,0.000231,0.000000,0.000000,0.000000
10,american cheese,0.000000,0.000000,0.003663,0.000000,0.001325,0.000000,0.000000,0.000000,0.000000,0.000638,0.000000,0.000000,0.000000,0.004194,0.000000,0.000000,0.000926,0.000000,0.000000,0.000000
11,anaheim chile,0.000000,0.000000,0.000000,0.000000,0.001325,0.000000,0.000000,0.000333,0.000000,0.000000,0.000000,0.000000,0.000000,0.005747,0.002436,0.000000,0.000463,0.003033,0.003249,0.000000
12,ancho,0.002141,0.000000,0.003663,0.000000,0.000000,0.000378,0.000000,0.000333,0.000000,0.000128,0.000000,0.000000,0.000000,0.033551,0.002436,0.002045,0.001852,0.011122,0.000650,0.000000
13,ancho chile pepper,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,anchovy,0.000000,0.001244,0.009158,0.000000,0.000000,0.026833,0.004255,0.000000,0.000000,0.025772,0.000000,0.001405,0.022892,0.000777,0.001218,0.002045,0.000000,0.010111,0.001949,0.000000
15,anchovy paste,0.000000,0.000000,0.005495,0.000000,0.000000,0.004157,0.001702,0.000000,0.000000,0.005996,0.000000,0.000000,0.000000,0.000155,0.000000,0.000000,0.000000,0.000000,0.001949,0.000000
16,andouille sausage,0.002141,0.000000,0.417582,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000255,0.000000,0.000000,0.000000,0.000311,0.000000,0.000000,0.008333,0.006067,0.000000,0.000000
17,angel hair,0.000000,0.000000,0.007326,0.001496,0.002649,0.000756,0.003404,0.000000,0.000000,0.008548,0.001901,0.001405,0.000000,0.000932,0.002436,0.000000,0.000000,0.002022,0.001949,0.000000
18,anise,0.004283,0.001244,0.000000,0.041526,0.017219,0.006047,0.008511,0.017316,0.004498,0.005231,0.005703,0.003514,0.001205,0.006213,0.010962,0.002045,0.001157,0.005056,0.007797,0.078788
19,anise seed,0.002141,0.000000,0.000000,0.000374,0.000000,0.001512,0.003404,0.000999,0.001499,0.001659,0.001901,0.000000,0.000000,0.002796,0.006090,0.000000,0.000231,0.001011,0.000000,0.001212

In [170]:
prevalence_ratios = pct_counts.copy()

now compute overall percentages for each ingredient

In [171]:
#THIS IS WRONG... computing an average accross the entire 
#recipe dataset overweights the more prevalent cuisines
#now compute overall percentages for each ingredient
# ingredient_pcts = {}
# for ing in ingredient_counts.columns:
#     if ing == 'cuisine':
#         pass
#     else:
#         ing_count = ingredient_counts[ing].sum()
#         ing_pct = ing_count/recipe_total
#         #print (ing, ing_count, ing_pct )
#         ingredient_pcts[ing] = ing_pct

# for i, row in ic2.iterrows():
#     #print(i, row['ingredient'])
#     for key, val in cuisine_counts.items():
#         #key - the cuisine
#         #row[key] - percentage of recipes in that cuisione with that ingredient
#         #ingredient_pcts[row['ingredient]] - percentage across all cuisines 
#         if ingredient_pcts[row['ingredient']] == 0:
#             relative_ratio = 0
#         else:    
#            relative_ratio = row[key] / ingredient_pcts[row['ingredient']]
#         #print (key, row[key], ingredient_pcts[row['ingredient']], relative_ratio) 
#         ic2.loc[i, key] = relative_ratio

In [172]:
prevalence_ratios['avg'] = np.nan
for i, row in prevalence_ratios.iterrows():
    #print (row.ingredient, row[1:21].mean())
    avg = row[1:21].mean()
    prevalence_ratios.loc[i, 'avg'] = avg
    for cuisine in cuisine_counts.keys():
        #print (cuisine, row[cuisine], avg, row[cuisine] / avg)
        if avg == 0:
            relative_ratio = 0
        else:    
            relative_ratio = row[cuisine] / avg
        prevalence_ratios.loc[i, cuisine] = relative_ratio

In [173]:
prevalence_ratios.head(40)

cuisine,ingredient,brazilian,british,cajun_creole,chinese,filipino,french,greek,indian,irish,italian,jamaican,japanese,korean,mexican,moroccan,russian,southern_us,spanish,thai,vietnamese,avg
0,active yeast,0.506923,1.275924,5.202923,0.354258,0.731625,1.192910,0.402950,0.893431,0.118307,1.288672,0.300042,0.110908,0.000000,0.208370,0.768926,5.648026,0.529727,0.319155,0.051274,0.095650,0.012673
1,adobo sauce,0.000000,0.000000,0.000000,0.000000,1.371529,0.000000,0.000000,0.344823,1.552480,0.132113,1.968639,0.000000,0.000000,13.671615,0.000000,0.000000,0.958800,0.000000,0.000000,0.000000,0.000966
2,agave nectar,3.407026,0.000000,0.000000,0.595242,0.000000,0.150329,0.677056,0.529830,0.000000,0.101498,0.000000,3.074823,2.875447,1.729973,0.000000,1.626872,0.644535,0.402194,1.292301,2.892874,0.002514
3,alfredo sauce,0.000000,0.000000,10.041753,0.000000,0.000000,0.414422,0.000000,0.000000,0.000000,9.373499,0.000000,0.000000,0.000000,0.170326,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000912
4,allspice,0.068419,1.072999,1.053347,0.000000,0.042320,0.458865,0.870169,0.255357,0.958066,0.048918,11.845144,0.022454,0.000000,0.327555,1.712383,0.522724,0.436375,0.129228,0.020761,0.154916,0.031297
5,almond,1.528444,1.627616,0.653648,0.511816,0.078784,1.978236,0.734033,1.228066,0.579659,1.009326,0.169625,0.271703,0.035832,0.383427,4.021009,1.581320,0.481914,2.826746,0.154599,0.144199,0.033624
6,almond extract,0.000000,3.343319,0.895114,0.731362,0.323664,4.063535,0.623914,0.081374,2.564563,1.745918,0.464575,0.343452,0.000000,0.227741,0.297645,2.498632,1.301024,0.494168,0.000000,0.000000,0.004092
7,almond flour,0.000000,1.056741,1.556080,1.589263,0.000000,4.174247,0.000000,1.131695,0.000000,1.625963,1.615247,0.597062,0.000000,0.527878,0.000000,0.000000,1.966713,2.577209,0.552060,1.029842,0.001177
8,almond milk,15.054660,0.672649,0.000000,0.000000,0.000000,0.613163,0.000000,1.440718,0.000000,0.413991,0.000000,0.380049,0.000000,0.252008,0.000000,0.000000,0.625937,0.546825,0.000000,0.000000,0.001849
9,amchur,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.071802,0.000000,0.000000,0.000000,6.796506,0.000000,0.000000,0.000000,0.000000,0.131692,0.000000,0.000000,0.000000,0.001758
10,american cheese,0.000000,0.000000,6.817935,0.000000,2.465293,0.000000,0.000000,0.000000,0.000000,1.187354,0.000000,0.000000,0.000000,7.805995,0.000000,0.000000,1.723422,0.000000,0.000000,0.000000,0.000537
11,anaheim chile,0.000000,0.000000,0.000000,0.000000,1.597146,0.000000,0.000000,0.401547,0.000000,0.000000,0.000000,0.000000,0.000000,6.930145,2.937504,0.000000,0.558262,3.657771,3.917626,0.000000,0.000829
12,ancho,0.734606,0.000000,1.256634,0.000000,0.000000,0.129653,0.000000,0.114239,0.000000,0.043769,0.000000,0.000000,0.000000,11.509972,0.835715,0.701556,0.635298,3.815644,0.222912,0.000000,0.002915
13,ancho chile pepper,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,anchovy,0.000000,0.231060,1.701211,0.000000,0.000000,4.984819,0.790520,0.000000,0.000000,4.787701,0.000000,0.261099,4.252618,0.144278,0.226276,0.379902,0.000000,1.878385,0.362129,0.000000,0.005383
15,anchovy paste,0.000000,0.000000,5.648447,0.000000,0.000000,4.273693,1.749817,0.000000,0.000000,6.164432,0.000000,0.000000,0.000000,0.159680,0.000000,0.000000,0.000000,0.000000,2.003932,0.000000,0.000973
16,andouille sausage,0.098522,0.000000,19.212900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011740,0.000000,0.000000,0.000000,0.014293,0.000000,0.000000,0.383415,0.279129,0.000000,0.000000,0.021734
17,angel hair,0.000000,0.000000,4.207221,0.859387,1.521286,0.434078,1.955015,0.000000,0.000000,4.909050,1.091798,0.807148,0.000000,0.535215,1.398991,0.000000,0.000000,1.161346,1.119465,0.000000,0.001741
18,anise,0.375155,0.108954,0.000000,3.637655,1.508321,0.529697,0.745520,1.516860,0.393997,0.458222,0.499612,0.307796,0.105541,0.544260,0.960278,0.179138,0.101387,0.442865,0.683030,6.901712,0.011416
19,anise seed,1.724780,0.000000,0.000000,0.301337,0.000000,1.217645,2.742034,0.804668,1.207605,1.335946,1.531316,0.000000,0.000000,2.252020,4.905435,0.000000,0.186452,0.814431,0.000000,0.976330,0.001242
20,apple,0.849587,1.480438,1.089993,0.385922,1.261215,1.919310,0.168833,0.607753,1.903483,0.182231,0.603433,0.501871,1.529667,0.566972,0.338283,2.515230,2.139918,0.962808,0.464044,0.529010,0.025204
21,apple cider,0.280618,0.162996,1.440097,1.127618,3.471492,0.643853,0.223062,0.392754,1.178850,0.183916,1.743996,0.460467,0.947341,1.404531,0.319242,0.803980,3.336891,0.000000,0.766367,1.111929,0.007631
22,apple juice,1.123862,0.000000,0.000000,0.196350,0.000000,0.991768,0.000000,0.524319,4.721232,0.401769,0.000000,0.000000,4.426392,0.326091,0.639274,1.073300,2.429832,2.122725,1.023087,0.000000,0.001905
23,apricot,0.192756,1.567465,0.000000,0.134706,0.119228,1.258745,0.229831,0.419661,1.079667,0.367511,0.000000,0.063259,0.108455,0.097875,10.416125,2.761265,0.229211,0.728148,0.116981,0.109112,0.011109
24,arborio rice,0.000000,0.000000,1.738524,0.118373,0.419088,0.119581,0.000000,0.000000,0.000000,10.617016,0.000000,0.000000,0.000000,0.049147,0.000000,0.000000,0.219730,6.718541,0.000000,0.000000,0.003160
25,artichoke,0.000000,0.236470,3.482091,0.000000,0.000000,2.011875,4.692377,0.000000,0.000000,4.535959,0.000000,0.133607,0.000000,0.118125,1.389443,0.000000,0.132029,3.268025,0.000000,0.000000,0.005260
26,artichoke heart,0.000000,0.000000,2.245807,0.000000,0.000000,1.969537,5.478814,0.000000,0.000000,5.514663,0.000000,0.000000,0.000000,0.190465,1.120168,0.000000,0.070961,3.409585,0.000000,0.000000,0.003262
27,arugula,0.000000,1.124197,1.103607,0.112714,0.000000,1.480235,2.564125,0.100328,0.000000,6.150236,0.000000,1.270350,0.725987,0.280787,2.568810,0.616124,0.488193,1.218543,0.195767,0.000000,0.003319
28,asafetida,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.709039,0.000000,0.000000,0.000000,5.053175,0.000000,0.000000,0.000000,0.000000,0.237787,0.000000,0.000000,0.000000,0.000973
29,asafoetida,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.752217,0.000000,0.000000,0.000000,2.247783,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001876
30,asiago,0.000000,0.000000,2.209964,0.000000,0.000000,2.280122,0.000000,0.000000,1.809056,11.084221,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.396575,1.220061,0.000000,0.000000,0.000829
31,asparagu,0.000000,0.190736,1.685180,1.147410,0.000000,2.781884,0.261024,0.306396,0.689736,3.443460,0.000000,2.478624,1.478085,0.238197,0.186786,0.313602,0.212988,1.550570,2.291801,0.743522,0.006521
32,asparagu spear,0.000000,0.000000,1.357902,0.832115,0.000000,3.922829,0.000000,0.000000,2.223133,2.270216,0.000000,4.168178,1.786541,0.345487,0.000000,0.000000,0.000000,0.749661,1.445253,0.898684,0.001349
33,avocado,1.273318,0.000000,0.435634,0.200215,0.236281,0.067419,0.303646,0.099008,0.178303,0.189666,0.678296,2.507265,0.143287,10.187754,0.144857,0.243206,0.178943,1.382883,0.540933,1.009086,0.016817
34,bacon,2.109517,1.021086,3.728873,0.319413,0.173977,1.799520,0.083842,0.000000,3.101653,0.976178,0.624299,0.184614,0.316512,0.647786,0.000000,0.738690,3.276213,0.796881,0.021337,0.079608,0.030452
35,bacon dripping,0.000000,1.576648,8.125800,0.000000,0.839487,0.479072,0.000000,0.000000,0.950244,0.000000,0.000000,0.000000,0.000000,0.492243,0.000000,0.000000,6.895644,0.640862,0.000000,0.000000,0.001578
36,baguette,0.539529,0.000000,2.538058,0.047131,0.000000,3.713695,0.321651,0.041951,0.377751,2.459165,0.000000,0.088531,0.000000,0.117409,0.153447,0.000000,0.379106,3.948816,0.081858,5.191902,0.007938
37,baking,0.469020,3.068401,1.309041,0.431276,0.458067,0.544596,0.667153,0.418433,4.407260,0.429469,1.073902,0.445566,0.138892,0.392146,0.154456,1.744525,3.284949,0.384656,0.052434,0.125760,0.086745
38,baking potato,0.000000,2.223812,1.007577,0.051453,0.000000,1.923192,1.404605,1.053376,4.742559,0.596602,0.000000,0.000000,0.000000,0.213629,0.335041,3.093817,0.573059,2.781279,0.000000,0.000000,0.007271
39,baking soda,0.370150,3.138997,1.456328,0.594953,0.091581,0.209052,0.500190,0.425962,5.960683,0.299935,0.722988,0.388722,0.208265,0.166470,0.000000,1.696784,3.577238,0.104869,0.044928,0.041905,0.028925

In [174]:
for cuisine in cuisine_counts.keys():
    print(cuisine)

brazilian
british
cajun_creole
chinese
filipino
french
greek
indian
irish
italian
jamaican
japanese
korean
mexican
moroccan
russian
southern_us
spanish
thai
vietnamese

In [175]:
prevalence_ratios[['ingredient','brazilian']].sort_values('brazilian',ascending=False).head(10)

cuisine       ingredient  brazilian
114              cachaca  20.000000
8            almond milk  15.054660
834        tapioca flour  13.033896
799             sprinkle  10.169709
771         simple syrup   9.810379
835       tapioca starch   9.129978
219       condensed milk   8.412668
814      superfine sugar   8.147710
434             key lime   7.094462
72            black bean   6.633678

In [176]:
prevalence_ratios[['ingredient','british']].sort_values('british',ascending=False).head(10)

cuisine      ingredient    british
353        golden syrup  16.660127
276        double cream  12.331458
519         mixed spice  10.609049
585         pastry puff   8.512946
264             currant   8.095681
701          rolled oat   8.034964
665         puff pastry   8.007904
478        malt vinegar   7.455985
355      graham cracker   7.372087
358       grand marnier   6.837118

In [177]:
prevalence_ratios[['ingredient','cajun_creole']].sort_values('cajun_creole',ascending=False).head(10)

cuisine         ingredient  cajun_creole
308                   file     19.865494
115        cajun seasoning     19.338700
254       creole seasoning     19.268229
16       andouille sausage     19.212900
253         creole mustard     18.607071
247               crawfish     18.104390
780         smoked sausage     17.880724
546                   okra     14.986103
130         catfish fillet     14.870321
745              seasoning     14.139487

In [178]:
prevalence_ratios[['ingredient','chinese']].sort_values('chinese',ascending=False).head(10)

cuisine           ingredient    chinese
303          fermented black  20.000000
825      szechwan peppercorn  17.932449
189                chow mein  17.310654
758            shaoxing wine  16.833215
81             black vinegar  16.175565
316               five spice  13.381917
480          mandarin orange  11.621275
282         dumpling wrapper  11.106715
907           wonton wrapper  11.069160
893           water chestnut  10.843581

In [179]:
prevalence_ratios[['ingredient','filipino']].sort_values('filipino',ascending=False).head(10)

cuisine       ingredient   filipino
140              chayote  13.045494
347        glutinou rice  10.084641
640           pork belly   8.821861
769         shrimp paste   8.747703
619      pineapple chunk   7.628808
59            beef shank   7.212414
654        powdered milk   6.795297
700         roll wrapper   6.586729
206        coconut cream   6.158839
641            pork butt   5.731952

In [180]:
prevalence_ratios[['ingredient','french']].sort_values('french',ascending=False).head(10)

cuisine      ingredient     french
385             gruyère  16.002614
384      gruyere cheese  15.300329
99          brie cheese  14.860179
270         de provence  10.964360
215              cognac  10.666840
393        haricot vert  10.211675
823         swis cheese   9.373758
358       grand marnier   9.348713
836            tarragon   9.273547
593         pearl onion   8.834360

In [181]:
prevalence_ratios[['ingredient','greek']].sort_values('greek',ascending=False).head(10)

cuisine       ingredient      greek
368      greek seasoning  19.403674
304          feta cheese  17.631974
624                 pita  16.310716
625           pita bread  16.131310
607         phyllo dough  13.099178
429       kalamata olive  12.768651
428             kalamata  12.116811
561                 orzo  11.598318
369         greek yogurt  11.146029
514           mint flake  10.982036

In [182]:
prevalence_ratios[['ingredient','indian']].sort_values('indian',ascending=False).head(10)

cuisine      ingredient     indian
868            urad dal  18.847139
75        black mustard  18.284583
29           asafoetida  17.752217
357          gram flour  17.603304
569              paneer  17.296577
333        garam masala  17.022286
490              masala  16.920502
302           fenugreek  16.856130
420             jaggery  16.734017
163      chickpea flour  16.262153

In [183]:
prevalence_ratios[['ingredient','irish']].sort_values('irish',ascending=False).head(10)

cuisine      ingredient      irish
412       irish whiskey  19.175450
233         corned beef  15.423777
56         beef brisket  10.896447
492       mashed potato  10.099121
592        pearl barley   8.943222
902             whiskey   8.759590
898         wheat flour   7.943178
469             liqueur   7.930646
701          rolled oat   6.779727
183      chocolate chip   6.624380

In [184]:
prevalence_ratios[['ingredient','italian']].sort_values('italian',ascending=False).head(10)

cuisine       ingredient    italian
348              gnocchi  20.000000
101        broccoli rabe  18.825495
486       marinara sauce  16.608556
582          pasta shell  16.167911
443       lasagna noodle  15.869883
606                pesto  14.878290
694             rigatoni  14.845468
853           tortellini  14.773372
596      pecorino romano  14.716509
693       ricotta cheese  14.557840

In [185]:
prevalence_ratios[['ingredient','jamaican']].sort_values('jamaican',ascending=False).head(10)

cuisine       ingredient   jamaican
741        scotch bonnet  18.662653
388      habanero pepper  16.854383
4               allspice  11.845144
710                  rum  11.440904
629             plantain   8.439005
848       tomato ketchup   8.249883
910                  yam   8.194589
68                berrie   7.090038
478         malt vinegar   6.964590
620      pineapple juice   6.662645

In [186]:
prevalence_ratios[['ingredient','japanese']].sort_values('japanese',ascending=False).head(10)

cuisine    ingredient   japanese
891      wasabi paste  19.884340
88       bonito flake  19.633264
437             konbu  19.218338
268             dashi  18.903106
890            wasabi  18.660672
335              gari  17.102154
716              sake  16.896478
516              miso  16.744592
539              nori  16.340665
517        miso paste  15.919718

In [187]:
prevalence_ratios[['ingredient','korean']].sort_values('korean',ascending=False).head(10)

cuisine       ingredient     korean
350            gochugaru  20.000000
436               kimchi  19.651063
351            gochujang  19.521585
683            rice cake  18.193235
44                  base  15.198773
591                 pear  12.063208
755               sesame   8.761346
756           sesame oil   8.008261
294            enokitake   7.856592
565      oyster mushroom   7.782597

In [188]:
prevalence_ratios[['ingredient','mexican']].sort_values('mexican',ascending=False).head(10)

cuisine         ingredient    mexican
499           mexican beer  20.000000
501      mexican chocolate  20.000000
827             taco sauce  20.000000
292        enchilada sauce  19.925763
679           refried bean  19.553387
828         taco seasoning  19.545606
503        mexican oregano  19.368108
725            salsa verde  19.112867
579          pasilla chile  19.053500
489            masa harina  18.830709

In [189]:
prevalence_ratios[['ingredient','moroccan']].sort_values('moroccan',ascending=False).head(10)

cuisine       ingredient   moroccan
660      preserved lemon  19.443454
394              harissa  19.177320
241              couscou  17.541391
322         flower water  13.417313
664                prune  11.125835
162             chickpea  10.437182
23               apricot  10.416125
441        lamb shoulder   9.577349
440           lamb shank   9.106026
448             leg lamb   8.815954

In [190]:
prevalence_ratios[['ingredient','russian']].sort_values('russian',ascending=False).head(10)

cuisine      ingredient    russian
65                 beet  14.825183
136         celery root  10.857059
273         dill pickle  10.314269
238      cottage cheese  10.210108
274            dillweed   9.710540
272                dill   9.703913
636               poppy   9.269208
779       smoked salmon   7.896720
124             caraway   7.517056
235           cornichon   7.050734

In [191]:
prevalence_ratios[['ingredient','southern_us']].sort_values('southern_us',ascending=False).head(10)

cuisine        ingredient  southern_us
240           country ham    17.959393
512      mini marshmallow    14.649829
873         vanilla wafer    14.149470
614             pie shell    12.544980
90        bourbon whiskey    12.517970
383                  grit    11.738923
382          green tomato    10.773335
587                peache    10.729411
185            chop pecan    10.561533
434              key lime     9.970018

In [192]:
prevalence_ratios[['ingredient','spanish']].sort_values('spanish',ascending=False).head(10)

cuisine       ingredient    spanish
791      spanish chorizo  17.738137
479      manchego cheese  16.899289
793      spanish paprika  16.361773
188      chorizo sausage  12.378269
763       sherry vinegar  12.305277
187              chorizo  12.239623
472      littleneck clam   9.513130
239        country bread   9.449654
397      heirloom tomato   9.240511
856           triple sec   8.927872

In [193]:
prevalence_ratios[['ingredient','thai']].sort_values('thai',ascending=False).head(10)

cuisine      ingredient       thai
375         green curry  19.000279
332            galangal  18.608400
266         curry paste  17.182031
807      straw mushroom  15.919292
427         kaffir lime  15.906822
567          palm sugar  14.660376
833      tamarind paste  12.108833
589       peanut butter  11.967106
450          lemon gras  11.460687
457           lemongras  10.091535

In [194]:
prevalence_ratios[['ingredient','vietnamese']].sort_values('vietnamese',ascending=False).head(10)

cuisine       ingredient  vietnamese
686           rice paper   16.165381
688      rice vermicelli   15.025810
697           rock sugar   12.740472
882           vermicelli   12.350494
908             wood ear   11.445955
69            bird chile   10.207015
685          rice noodle    8.677374
314           fish sauce    8.649910
803           star anise    8.545311
52            beansprout    8.523703

# Similarity of cuisines

Try using cosine similarity to find most similar cuisines

In [195]:
from sklearn.metrics.pairwise import cosine_similarity

In [196]:
pr2 = prevalence_ratios.T.reset_index().iloc[1:]
pr2 = pr2.set_index('cuisine')
pr2 = pr2.iloc[0:20,:]

In [197]:
#pr2

In [198]:
cuisine_sim = pd.DataFrame(
    cosine_similarity(pr2),
    columns=pr2.index,
    index=pr2.index
)

In [199]:
cuisine_sim

cuisine,brazilian,british,cajun_creole,chinese,filipino,french,greek,indian,irish,italian,jamaican,japanese,korean,mexican,moroccan,russian,southern_us,spanish,thai,vietnamese
cuisine,,,,,,,,,,,,,,,,,,,,
brazilian,1.000000,0.192706,0.200489,0.106572,0.215039,0.178016,0.070197,0.100748,0.179683,0.096170,0.243711,0.075414,0.093975,0.129335,0.100608,0.177645,0.225247,0.208447,0.161978,0.151362
british,0.192706,1.000000,0.212391,0.109229,0.153778,0.425554,0.131845,0.121560,0.436757,0.170062,0.228213,0.087590,0.081827,0.057058,0.178349,0.346271,0.331353,0.185021,0.070075,0.084465
cajun_creole,0.200489,0.212391,1.000000,0.125856,0.207012,0.257373,0.179607,0.081193,0.205890,0.258676,0.222319,0.086341,0.094362,0.169694,0.135684,0.218055,0.355315,0.251451,0.121436,0.136800
chinese,0.106572,0.109229,0.125856,1.000000,0.337562,0.111570,0.062149,0.103551,0.087901,0.065565,0.162103,0.240425,0.298195,0.057137,0.079855,0.110180,0.099965,0.084497,0.309015,0.404357
filipino,0.215039,0.153778,0.207012,0.337562,1.000000,0.144930,0.091171,0.104203,0.137779,0.095606,0.251716,0.140358,0.209632,0.110793,0.098647,0.153636,0.175599,0.140515,0.299085,0.346230
french,0.178016,0.425554,0.257373,0.111570,0.144930,1.000000,0.210034,0.075250,0.306798,0.298912,0.148132,0.093030,0.089134,0.069984,0.193745,0.343743,0.250593,0.319836,0.097383,0.119206
greek,0.070197,0.131845,0.179607,0.062149,0.091171,0.210034,1.000000,0.106536,0.129090,0.283056,0.100395,0.066250,0.066075,0.079985,0.294145,0.195103,0.122775,0.194687,0.087598,0.095892
indian,0.100748,0.121560,0.081193,0.103551,0.104203,0.075250,0.106536,1.000000,0.093343,0.040335,0.146529,0.178675,0.053294,0.045090,0.196128,0.113306,0.068210,0.085324,0.176227,0.115502
irish,0.179683,0.436757,0.205890,0.087901,0.137779,0.306798,0.129090,0.093343,1.000000,0.140011,0.166332,0.072130,0.083514,0.063412,0.157464,0.338999,0.307575,0.157185,0.061001,0.081056
italian,0.096170,0.170062,0.258676,0.065565,0.095606,0.298912,0.283056,0.040335,0.140011,1.000000,0.091411,0.052651,0.047551,0.076348,0.120003,0.158716,0.143780,0.232126,0.070546,0.059205
jamaican,0.243711,0.228213,0.222319,0.162103,0.251716,0.148132,0.100395,0.146529,0.166332,0.091411,1.000000,0.084305,0.104156,0.110038,0.145522,0.158368,0.210894,0.144822,0.178210,0.148908
japanese,0.075414,0.087590,0.086341,0.240425,0.140358,0.093030,0.066250,0.178675,0.072130,0.052651,0.084305,1.000000,0.292267,0.033406,0.076012,0.117713,0.065020,0.067833,0.174209,0.177402
korean,0.093975,0.081827,0.094362,0.298195,0.209632,0.089134,0.066075,0.053294,0.083514,0.047551,0.104156,0.292267,1.000000,0.053046,0.067626,0.096267,0.076265,0.083913,0.205099,0.294012
mexican,0.129335,0.057058,0.169694,0.057137,0.110793,0.069984,0.079985,0.045090,0.063412,0.076348,0.110038,0.033406,0.053046,1.000000,0.069072,0.067983,0.156632,0.143699,0.077928,0.080151
moroccan,0.100608,0.178349,0.135684,0.079855,0.098647,0.193745,0.294145,0.196128,0.157464,0.120003,0.145522,0.076012,0.067626,0.069072,1.000000,0.194540,0.096254,0.243737,0.107316,0.095497
russian,0.177645,0.346271,0.218055,0.110180,0.153636,0.343743,0.195103,0.113306,0.338999,0.158716,0.158368,0.117713,0.096267,0.067983,0.194540,1.000000,0.175326,0.186253,0.074779,0.114539
southern_us,0.225247,0.331353,0.355315,0.099965,0.175599,0.250593,0.122775,0.068210,0.307575,0.143780,0.210894,0.065020,0.076265,0.156632,0.096254,0.175326,1.000000,0.167704,0.085340,0.077479
spanish,0.208447,0.185021,0.251451,0.084497,0.140515,0.319836,0.194687,0.085324,0.157185,0.232126,0.144822,0.067833,0.083913,0.143699,0.243737,0.186253,0.167704,1.000000,0.103852,0.112671
thai,0.161978,0.070075,0.121436,0.309015,0.299085,0.097383,0.087598,0.176227,0.061001,0.070546,0.178210,0.174209,0.205099,0.077928,0.107316,0.074779,0.085340,0.103852,1.000000,0.511236
vietnamese,0.151362,0.084465,0.136800,0.404357,0.346230,0.119206,0.095892,0.115502,0.081056,0.059205,0.148908,0.177402,0.294012,0.080151,0.095497,0.114539,0.077479,0.112671,0.511236,1.000000

In [200]:
for cuisine in cuisine_counts.keys():
    print(cuisine_sim[cuisine].sort_values(ascending=False).head(10))

cuisine
brazilian       1.000000
jamaican        0.243711
southern_us     0.225247
filipino        0.215039
spanish         0.208447
cajun_creole    0.200489
british         0.192706
irish           0.179683
french          0.178016
russian         0.177645
Name: brazilian, dtype: float64
cuisine
british         1.000000
irish           0.436757
french          0.425554
russian         0.346271
southern_us     0.331353
jamaican        0.228213
cajun_creole    0.212391
brazilian       0.192706
spanish         0.185021
moroccan        0.178349
Name: british, dtype: float64
cuisine
cajun_creole    1.000000
southern_us     0.355315
italian         0.258676
french          0.257373
spanish         0.251451
jamaican        0.222319
russian         0.218055
british         0.212391
filipino        0.207012
irish           0.205890
Name: cajun_creole, dtype: float64
cuisine
chinese         1.000000
vietnamese      0.404357
filipino        0.337562
thai            0.309015
korean          0.298195
japanese        0.240425
jamaican        0.162103
cajun_creole    0.125856
french          0.111570
russian         0.110180
Name: chinese, dtype: float64
cuisine
filipino        1.000000
vietnamese      0.346230
chinese         0.337562
thai            0.299085
jamaican        0.251716
brazilian       0.215039
korean          0.209632
cajun_creole    0.207012
southern_us     0.175599
british         0.153778
Name: filipino, dtype: float64
cuisine
french          1.000000
british         0.425554
russian         0.343743
spanish         0.319836
irish           0.306798
italian         0.298912
cajun_creole    0.257373
southern_us     0.250593
greek           0.210034
moroccan        0.193745
Name: french, dtype: float64
cuisine
greek           1.000000
moroccan        0.294145
italian         0.283056
french          0.210034
russian         0.195103
spanish         0.194687
cajun_creole    0.179607
british         0.131845
irish           0.129090
southern_us     0.122775
Name: greek, dtype: float64
cuisine
indian        1.000000
moroccan      0.196128
japanese      0.178675
thai          0.176227
jamaican      0.146529
british       0.121560
vietnamese    0.115502
russian       0.113306
greek         0.106536
filipino      0.104203
Name: indian, dtype: float64
cuisine
irish           1.000000
british         0.436757
russian         0.338999
southern_us     0.307575
french          0.306798
cajun_creole    0.205890
brazilian       0.179683
jamaican        0.166332
moroccan        0.157464
spanish         0.157185
Name: irish, dtype: float64
cuisine
italian         1.000000
french          0.298912
greek           0.283056
cajun_creole    0.258676
spanish         0.232126
british         0.170062
russian         0.158716
southern_us     0.143780
irish           0.140011
moroccan        0.120003
Name: italian, dtype: float64
cuisine
jamaican        1.000000
filipino        0.251716
brazilian       0.243711
british         0.228213
cajun_creole    0.222319
southern_us     0.210894
thai            0.178210
irish           0.166332
chinese         0.162103
russian         0.158368
Name: jamaican, dtype: float64
cuisine
japanese      1.000000
korean        0.292267
chinese       0.240425
indian        0.178675
vietnamese    0.177402
thai          0.174209
filipino      0.140358
russian       0.117713
french        0.093030
british       0.087590
Name: japanese, dtype: float64
cuisine
korean          1.000000
chinese         0.298195
vietnamese      0.294012
japanese        0.292267
filipino        0.209632
thai            0.205099
jamaican        0.104156
russian         0.096267
cajun_creole    0.094362
brazilian       0.093975
Name: korean, dtype: float64
cuisine
mexican         1.000000
cajun_creole    0.169694
southern_us     0.156632
spanish         0.143699
brazilian       0.129335
filipino        0.110793
jamaican        0.110038
vietnamese      0.080151
greek           0.079985
thai            0.077928
Name: mexican, dtype: float64
cuisine
moroccan        1.000000
greek           0.294145
spanish         0.243737
indian          0.196128
russian         0.194540
french          0.193745
british         0.178349
irish           0.157464
jamaican        0.145522
cajun_creole    0.135684
Name: moroccan, dtype: float64
cuisine
russian         1.000000
british         0.346271
french          0.343743
irish           0.338999
cajun_creole    0.218055
greek           0.195103
moroccan        0.194540
spanish         0.186253
brazilian       0.177645
southern_us     0.175326
Name: russian, dtype: float64
cuisine
southern_us     1.000000
cajun_creole    0.355315
british         0.331353
irish           0.307575
french          0.250593
brazilian       0.225247
jamaican        0.210894
filipino        0.175599
russian         0.175326
spanish         0.167704
Name: southern_us, dtype: float64
cuisine
spanish         1.000000
french          0.319836
cajun_creole    0.251451
moroccan        0.243737
italian         0.232126
brazilian       0.208447
greek           0.194687
russian         0.186253
british         0.185021
southern_us     0.167704
Name: spanish, dtype: float64
cuisine
thai            1.000000
vietnamese      0.511236
chinese         0.309015
filipino        0.299085
korean          0.205099
jamaican        0.178210
indian          0.176227
japanese        0.174209
brazilian       0.161978
cajun_creole    0.121436
Name: thai, dtype: float64
cuisine
vietnamese      1.000000
thai            0.511236
chinese         0.404357
filipino        0.346230
korean          0.294012
japanese        0.177402
brazilian       0.151362
jamaican        0.148908
cajun_creole    0.136800
french          0.119206
Name: vietnamese, dtype: float64

Most similar cuisines:

thai - vietnamese: .51

british - irish: .44

french - british: .43

chinese - vietnamese: .40

southern us - cajun-creole: .36

In [201]:
for cuisine in cuisine_counts.keys():
    print(cuisine_sim[cuisine].sort_values().head(1))

cuisine
greek    0.070197
Name: brazilian, dtype: float64
cuisine
mexican    0.057058
Name: british, dtype: float64
cuisine
indian    0.081193
Name: cajun_creole, dtype: float64
cuisine
mexican    0.057137
Name: chinese, dtype: float64
cuisine
greek    0.091171
Name: filipino, dtype: float64
cuisine
mexican    0.069984
Name: french, dtype: float64
cuisine
chinese    0.062149
Name: greek, dtype: float64
cuisine
italian    0.040335
Name: indian, dtype: float64
cuisine
thai    0.061001
Name: irish, dtype: float64
cuisine
indian    0.040335
Name: italian, dtype: float64
cuisine
japanese    0.084305
Name: jamaican, dtype: float64
cuisine
mexican    0.033406
Name: japanese, dtype: float64
cuisine
italian    0.047551
Name: korean, dtype: float64
cuisine
japanese    0.033406
Name: mexican, dtype: float64
cuisine
korean    0.067626
Name: moroccan, dtype: float64
cuisine
mexican    0.067983
Name: russian, dtype: float64
cuisine
japanese    0.06502
Name: southern_us, dtype: float64
cuisine
japanese    0.067833
Name: spanish, dtype: float64
cuisine
irish    0.061001
Name: thai, dtype: float64
cuisine
italian    0.059205
Name: vietnamese, dtype: float64

Least similar cuisines:

mexican - japanese: .033

italian - indian: .040

korean - italian: .047

british - mexican: .057